### PR TITLE
fix(registry): add request timeouts and max_retries

### PR DESCRIPTION
**Pull request by bacongobbler**
replaces #9

### CODE REVIEW

**Comment by bacongobbler** [comment]
Seeing this when running:

> 12/Feb/2015:23:30:03 +0000 DEBUG: api_error: Timeout value connect was (5, 30), but it must be an int or float.

@aledbf could you please elaborate on what exactly these values were supposed to represent?

**Comment by bacongobbler** [comment]
Ah, I see now. In requests v2.3.0 they use a float to represent the timeout value, but in requests v2.5.1 you can specify a tuple for the connect and read timeouts.

**Comment by bacongobbler** [comment]
fixed. Ready for review! I'll make a PR on deis/deis to properly test this.

**Comment by carmstrong** [comment]
Code LGTM!

**Comment by mboersma** [comment]
Code LGTM.

**Pull request merged**
