### PR TITLE
feat(requests): pull timeout workaround

### PR DESCRIPTION
**Pull request by aledbf**
workaround for deis/deis#2916 

ping @carmstrong

### CODE REVIEW

**Comment by carmstrong** [comment]
@aledbf It also looks like we'l need to fix up some tests: https://travis-ci.org/deis/docker-registry/jobs/50240552

**Comment by bacongobbler** [comment]
@aledbf I'm gonna help take over this PR. There's a lot of cleanup and we need to explore how we can get the urllib session properly mocked in the unit tests.

**Comment by aledbf** [comment]
@bacongobbler thanks. There's only one error in the tests but I don't know how to trace it

**Comment by bacongobbler** [comment]
closing in favour of #10.

**Pull request closed without merging**
